### PR TITLE
Updates IP for Open RSC server

### PR DESCRIPTION
**Pull request by Cleako**

### CODE REVIEW

**Comment by link12765** [comment]
I can confirm that this is the new IP address of the rsc.vet

Do you think that this would be better off using the dns resolution instead of the IP itself? I have a feeling that you'd have to rebuild every time the website changes IPs

**Comment by misterhat** [comment]
Yup, DNS resolution would be the right solution.

**Comment by c01dc0ffee** [comment]
Outdated!

**Comment by TheKeynesian** [comment]
Could you please enlighten me as to how I can do that on the 3DS? There is no options menu upon launching the app at any point before the login screen.

**Comment by misterhat** [comment]
we since have DNS support so this should no longer be an issue: https://github.com/2003scape/rsc-c/commit/fe74fcac85b759a5bf5694deaa96e5a4f1eeb5c7

**Pull request closed without merging**
