### PR TITLE
Memory use optimizations and new low memory mode

### PR DESCRIPTION
**Pull request by alarixnia**
Minimum memory requirement is now 24-26MB when compiled with -Os -s and SDL 1.2, F2P content only. Around 26-29MB when loading the full P2P game. Probably can be either lower or higher depending on the OS.

- Disabled animations when lowmem is set
- Disabled sound effects when lowmem is set
- Disabled fluff on login screen when lowmem is set (RIP runescape logo)
- Added 8-bit sprite palette (needs USE_LOCOLOUR=1)
- Replace some textures with solid colours (needs USE_TOONSCAPE=1)
- Further optimized GameModel, Surface, Polygon structs
- Lower number of polygons allocated by default when lowmem is set, overflow checks for excess polygons
- ~~Load 3D models on-demand when lowmem is set~~ not worth it since we have to keep them all uncompressed in memory anyway.

### CODE REVIEW

**Comment by RetroGamer02** [comment]
If we could get RSC-C on to the DSi or Maybe Dreamcast that would be amazing ty so much for this.

**Comment by alarixnia** [comment]
Generating an 8-bit colour palette is going to be a hard problem. We need to preserve the behaviour where greyscale and pink can be re-shaded with different colours, but the colour maps generated by GIMP (and the 8-bit ones in common use) tend to lack a good number of greyscale shades.

**Comment by alarixnia** [comment]
2023-12-20-101018_512x346_scrot

**Comment by alarixnia** [comment]
Welcome to ToonScape.
2023-12-20-115927_512x346_scrot

**Comment by alarixnia** [comment]
I think at this point I need a new malloc implementation to make further gains...

**Pull request merged**
